- name: Coverage Robot Action
  # You may pin to the exact commit or the version.
  # uses: coverage-robot/action@aa213eec98834151eb70a2c3e65c0e3676da80dc
  uses: coverage-robot/action@v1.0.13
  with:
    # Multi-line selection of coverage files to upload
    files: 
    # Tag to use for the coverage upload
    tag: 
    # The authentication token to validate authenticity of uploads
    token: 
    # Tag to use for the coverage upload
    endpoint: # optional, default is https://api.coveragerobot.com/v1
    # The GitHub token used to communicate with the Github API
    github-token: # optional, default is ${{ github.token }}
